### ISSUE TITLE
What is the purpose of <conf> column?

### ISSUE THREAD

**Issue by slavastar** [JonathonLuiten/TrackEval#119]
I am trying to compute MOT metrics. I logically assumed that the **conf** column describes the confidence of an observation (a float between 0 and 1).
However, recently I've found out that setting the **conf** column in a prediction dataset to random values between 0 and 1 always results in the same metric values. Therefore, it seems like this column is useless. Does somebody have the same issue?

PS: in my ground truth dataset the **conf** column contains only values of 1.

**Comment by jeethesh-pai** [comment]
This might be a possible copy of [issue](https://github.com/JonathonLuiten/TrackEval/issues/28#issue-855875046). Confidence column is usually ignored for evaluation. It just tells how sure the detector is about the presence of object. In ground truth it is set to 1 because human annotator is 100% confident that the object is present there.

**Comment by JonathonLuiten** [comment]
yes it is not used at all in tracking evaluation here. In previous MOTChallenge 'detection' (not tracking) benchmarks, this was used, and thus it is a remnant of that.
