### ISSUE TITLE
Is there any difference in the IDSW metric between TrackEval and motmetrics?

### ISSUE THREAD

**Issue by mesllo-bc** [JonathonLuiten/TrackEval#143]
Hi, I'm in the process of adapting HOTA for analyzing a tracker. I've always used the py-motmetrics for this but I'm now also comparing TrackEval. I noticed that the number of ID switches and fragmentations I get there is slightly different compared to the number of switches I get here. Here it seems that I get slightly more (2 or 3 more counts). I would like to understand whether I'm doing something wrong or if this is just because the way the switches and fragmentations are counted differ slightly between the two repos, and if so, if you can kindly shed some light on where I can find more info about this. Thank you!

**Comment by JonathonLuiten** [comment]
There was a small difference yes. This was because there was a bug in py-motmetrics, but here in this repo it is correct.

This was detailed in this issue on pymotmetrics:
https://github.com/cheind/py-motmetrics/issues/132

So in conclusion. Yes, there is a difference, here it is correct, there there is a bug.

I remember back in 2020 going in detail over what this bug was exactly and why, but I don't remember all the details right now

**Comment by maze2498** [comment]
I wanted to know if there is a way to also get information on at which frame the ID Switches occur. Is there way to modify the code to record this value as well?

Thank you!
