### ISSUE TITLE
GT files format for MOT

### ISSUE THREAD

**Issue by VladimirYugay** [JonathonLuiten/TrackEval#23]
In the description file, it's written that the ground truth/ prediction files should contain 10 values per row for MOT sequences (15, 16, 17, 20): [link](https://github.com/JonathonLuiten/TrackEval/blob/master/docs/MOTChallenge-format.txt). 

However, in the **data.zip** mentioned in the [README](https://github.com/JonathonLuiten/TrackEval), GT files *data/gt/mot_challenge/* MOT16-train, MOT17-train, MOT20-train contain only 9 values per row. 

Is it an intended thing or can be considered as an issue?

**Comment by JonathonLuiten** [comment]
That's a great question.

This doesn't have anything to do with this library but is actually from MOTChallenge itself, so maybe @dendorferpatrick or @aljosaosep wants to weigh in on the question.

So you are the correct the the official MOTChallenge read states that these should have 10 values:
<frame>, <id>, <bb_left>, <bb_top>, <bb_width>, <bb_height>, <conf>, <x>, <y>, <z>
but that the official MOTChallenge ground-truth files have 9 values.

What I myself can confirm, is that this is NO WAY influences the evaluation used in this code for MOTChallenge. E.g. the last 3 values (<x>, <y>, <z>) are never used, and whether they are there or not will not at all impact evaluation, nor cause any errors.

**Comment by JonathanSamelson** [comment]
Hi,

Thank you for your great work with the HOTA metrics.
I've a related issue but this is not about the difference between 9 and 10 values per line (even though I tried to remove one to see if it helps, but it does not). 

I tried your script with a GT file from the AICity challenge 2021 and compared it with a pred file they provide, both following the MOT format (attached to this message), but for some unknown reason, the script does not read the GT file, same as if it was empty:

```
Count: DeepSORT-SSD512-pedestrian  Dets      GT_Dets   IDs       GT_IDs
s01-c003                           14151     0         219       0
COMBINED                           14151     0         219       0
```

I tried to change some value, indexed by obj_id instead of frame_id, remove one '-1' at the end of each line, checked the encoding and also checked the entire file hierarchy.

Finally, I copied a GT file from a MOT sequence (MOT16-train\MOT16-02) and pasted it as it was my own GT file, even if it doesn't match at all... and it reads the GT file correctly:
```
Count: DeepSORT-SSD512-pedestrian  Dets      GT_Dets   IDs       GT_IDs
s01-c003                           14151     17833     219       54
COMBINED                           14151     17833     219       54
```

Here's the original GT file of the sequence I want to test:
[gt.txt](https://github.com/JonathonLuiten/TrackEval/files/6272112/gt.txt)

Here's one of the prediction file:
[s01-c003.txt](https://github.com/JonathonLuiten/TrackEval/files/6272130/s01-c003.txt)

Thank you in advance for your help.

**Comment by JonathonLuiten** [comment]
I have addressed @JonathanSamelson's problem in his comment in a separate issue. 

Since the original question of there being 9 and/or 10 datapoints is a non-issue (e.g. this doesn't cause any problems with the calculation of the metrics), I will close this issue now. Feel free to reopen it if you feel otherwise :)
