### ISSUE TITLE
How can I generate det.txt  file(as in MOT dataset) for my own data frames??

### ISSUE THREAD

**Issue by BakingBrains** [JonathonLuiten/TrackEval#27]

**Comment by JonathonLuiten** [comment]
By running a detector on the frames.

The MOT17 (now pretty old, from 2017), use the following three detectors:
DPM: https://motchallenge.net/method/DET=2&chl=9
FRCNN: https://motchallenge.net/method/DET=5&chl=9
SDP: https://motchallenge.net/method/DET=6&chl=9

However, since these are from 2017, all of these now perform much worse than the SOTA for 2021.

My personal recommendation for a 'strong' detector would be to use some of the the models from here:
https://github.com/facebookresearch/detectron2/blob/master/MODEL_ZOO.md
Note the models at the very bottom of the page are the strongest ones I would recommend.

There are also a number of other strong detection models. A few further links below:
https://github.com/google/automl/tree/master/efficientdet
https://github.com/facebookresearch/detr

Note that the detectors for MOTChallenge give 'amodal' bounding boxes (coving whole person, including non-visible parts), whereas these new stronger detectors are trained on COCO and thus give 'modal' detection results (only covering the visible part of the person). My recommendation if you want 'amodal' detections is to take one of these strong 'modal' detectors pre-trained on COCO, and fine-tune it on as much 'amodal' data you can find (including MOTChallenge train, but probably you also want more datasets, of which I am personally not sure what is out there).

I think this answers your question, so I am closing this now.

Jono

**Comment by joeyism** [comment]
@BakingBrains Did you happen to generate it and run it successfully? I'm going through the same process right now

**Comment by BakingBrains** [comment]
No, I paused that work for now. Did you able to generate? or are you still generating det.txt file?

**Comment by lmaple24327** [comment]
> @BakingBrains Did you happen to generate it and run it successfully? I'm going through the same process right now

Hello, may I ask if you have solved this problem
