### ISSUE TITLE
Negative values of MOTA, and Zeros of MOTP

### ISSUE THREAD

**Issue by Rajkumarsaswamy** [JonathonLuiten/TrackEval#32]
Hi,

Thank you for your great work. Its very helpful

I have evaluated People detection and tracking solution based on PeopleNet + KLT (nvtracker) using TrackEval on MOT Challenge in CLEAR metrics for data MOT20 training

Tracker outputs
[MOT20-01.txt](https://github.com/JonathonLuiten/TrackEval/files/6351884/MOT20-01.txt)
[MOT20-02.txt](https://github.com/JonathonLuiten/TrackEval/files/6351885/MOT20-02.txt)
[MOT20-03.txt](https://github.com/JonathonLuiten/TrackEval/files/6351887/MOT20-03.txt)
[MOT20-05.txt](https://github.com/JonathonLuiten/TrackEval/files/6351890/MOT20-05.txt)

Metric results
[pedestrian_detailed.csv](https://github.com/JonathonLuiten/TrackEval/files/6351906/pedestrian_detailed.csv)
[pedestrian_summary.txt](https://github.com/JonathonLuiten/TrackEval/files/6351907/pedestrian_summary.txt)

As can be seen in the attached results. I don’t understand why i have sometimes ‘-’ or ‘+’ in MOTA There are also 0 values of MOTP, which signals an error in calculations (?)

**Comment by JonathonLuiten** [comment]
MOTA is a really stupid metric (in my opinion), for a number of reasons, but one of those is that it allows negative values.

MOTA is calculated as (TP-FP-IDS)/(TP+FN). So if the number of (FP+IDS) is greater than the number of TPs the score will be negative. 

If you want more details on why MOTA is a stupid metric see my Section 9.1 (page 15) of my paper here: https://arxiv.org/pdf/2009.07736.pdf

As for MOTP being 0. This happens when there is no TPs.

My recommendation: stop using CLEAR and to use HOTA instead. :)

I think this answers your question, so will close this now. Feel free to reopen if you have remaining questions.

Cheers,
Jono

**Comment by brjathu** [comment]
Hi, Great work!

your code calculates MOTA as 

        res['MOTA'] = (res['CLR_TP'] - res['CLR_FP'] - res['IDSW']) / np.maximum(1.0, res['CLR_TP'] + res['CLR_FN'])

But the clear paper and your paper also says MOTA = 1 - sum(FP, FN, IDs)/GT

Why there is a difference in the code? Am I missing something?

Thanks.

**Comment by brjathu** [comment]
No worries, got it : )

**Comment by JonathonLuiten** [comment]
Glad that it's sorted :)
